import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Carousel from "../components/Carousel";
import Team from "../components/Team";
import styles from "../styles/Home.module.css";

type HomeProps = {
  children: React.ReactNode | React.ReactNode[];
};

const Home = ({ children }: HomeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>vHorus Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/pira.svg" />
      </Head>

      <header className={styles.link}>
        <Link href="/">Home</Link>
        <Link href="/flag">Flag</Link>
        <Link href="/steps">Steps</Link>
      </header>

      <main className={styles.main}>{children || <Team />}</main>

      <footer className={styles.footer}>
        From 🇩🇪 🇧🇴 🇨🇴 To 🇪🇬
        <span className={styles.logo}>
          <Image
            src="/static/pira.svg"
            alt="Piramid Logo"
            width={72}
            height={16}
          />
        </span>
        <b>vHorus Team</b>
      </footer>
    </div>
  );
};

export default Home;
