import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Carousel from "../components/Carousel";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>vHorus Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pira.svg" />
      </Head>

      <main className={styles.main}>
        <Carousel />
      </main>

      <footer className={styles.footer}>
        From 🇩🇪 🇧🇴 🇨🇴 To 🇪🇬
        <span className={styles.logo}>
          <Image src="/pira.svg" alt="Piramid Logo" width={72} height={16} />
        </span>
        <b>vHorus Team</b>
      </footer>
    </div>
  );
};

export default Home
